spring:
  application:
    name: course-service   # Service name (used in logs, Eureka, etc.)

  datasource:
    url: jdbc:mysql://localhost:3307/coursedb  # MySQL DB connection
    username: user
    password: user123

  jpa:
    hibernate:
      ddl-auto: update      # Auto schema update (not recommended for prod)
    show-sql: true

server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: "course-service"
    description:  "This is course service"
    version: "1.0"

